### ISSUE TITLE
Uploading a file on FE, then deleting it, then downloading it again seems not to populate frontend

### ISSUE THREAD

**Issue by dr-frmr** [bitful-pannul/file_transfer#4]
I can see the file exists and was successfully downloaded via terminal prints, but the frontend doesn't want to show it. Steps to repro:

1. Upload a file using UI on node A
2. On node B, search for node A and download the file from them
3. Delete the file on node A
4. On node A, search for node B and download the same file from them
5. File downloads successfully but doesn't show up

**Comment by dr-frmr** [comment]
```
got files from node: Address { node: "sepoliarocks.os", process: ProcessId { process-name: "http_server", package-name: "distro", publisher-node: "sys" } } ,files: [FileInfo { name: "kino_files:gloriainexcelsisdeo.os/files/kinode-aarch64-apple-darwin.zip", size: 12294106, dir: None }]
```
the backend prints this when I do the HTTP query, so it definitely seems to have the file on BE

**Comment by barraguda** [comment]
should be fixed with that runtime patch ^, reason was that the file was never created again with the vfs thinking it had an open handle of it already..

checking if anything similar can happen with other functions
